// data/local/radio_cache/radio_hive_model.dart
import 'package:hive/hive.dart';

part 'radio_model.g.dart'; // will be generated by build_runner

@HiveType(typeId: 0)
class RadioStation extends HiveObject {
  @HiveField(0)
  final String changeUuid;

  @HiveField(1)
  final String stationUuid;

  @HiveField(2)
  final String? serverUuid;

  @HiveField(3)
  final String name;

  @HiveField(4)
  final String url;

  @HiveField(5)
  final String urlResolved;

  @HiveField(6)
  final String homepage;

  @HiveField(7)
  final String favicon;

  @HiveField(8)
  final String tags;

  @HiveField(9)
  final String country;

  @HiveField(10)
  final String countryCode;

  @HiveField(11)
  final String state;

  @HiveField(12)
  final String language;

  @HiveField(13)
  final String languageCodes;

  @HiveField(14)
  final int votes;

  @HiveField(15)
  final String codec;

  @HiveField(16)
  final int bitrate;

  @HiveField(17)
  final bool hls;

  @HiveField(18)
  final bool lastCheckOk;

  @HiveField(19)
  bool favorite;

  @HiveField(20)
  final int clickCount;

  @HiveField(21)
  final int clickTrend;

  @HiveField(22)
  final DateTime lastChangeTime;

  @HiveField(23)
  final DateTime clickTime;

  RadioStation({
    required this.changeUuid,
    required this.stationUuid,
    required this.serverUuid,
    required this.name,
    required this.url,
    required this.urlResolved,
    required this.homepage,
    required this.favicon,
    required this.tags,
    required this.country,
    required this.countryCode,
    required this.state,
    required this.language,
    required this.languageCodes,
    required this.votes,
    required this.codec,
    required this.bitrate,
    required this.hls,
    required this.lastCheckOk,
    required this.clickCount,
    required this.clickTrend,
    required this.lastChangeTime,
    required this.clickTime,
    required this.favorite,
  });

  factory RadioStation.fromJson(Map<String, dynamic> json) {
    return RadioStation(
      changeUuid: json['changeuuid'] ?? '',
      stationUuid: json['stationuuid'] ?? '',
      serverUuid: json['serveruuid'],
      name: json['name'] ?? '',
      url: json['url'] ?? '',
      urlResolved: json['url_resolved'] ?? '',
      homepage: json['homepage'] ?? '',
      favicon: json['favicon'] ?? '',
      tags: json['tags'] ?? '',
      country: json['country'] ?? '',
      countryCode: json['countrycode'] ?? '',
      state: json['state'] ?? '',
      language: json['language'] ?? '',
      languageCodes: json['languagecodes'] ?? '',
      votes: json['votes'] ?? 0,
      codec: json['codec'] ?? '',
      bitrate: json['bitrate'] ?? 0,
      hls: json['hls'] == 1,
      lastCheckOk: json['lastcheckok'] == 1,
      clickCount: json['clickcount'] ?? 0,
      clickTrend: json['clicktrend'] ?? 0,
      lastChangeTime: json['lastchangetime_iso8601'] != null
          ? DateTime.parse(json['lastchangetime_iso8601'])
          : DateTime(1970),
      clickTime: json['clicktimestamp_iso8601'] != null
          ? DateTime.parse(json['clicktimestamp_iso8601'])
          : DateTime(1970),
      favorite: false,
    );
  }

  Map<String, dynamic> toJson() => {
        'changeuuid': changeUuid,
        'stationuuid': stationUuid,
        'serveruuid': serverUuid,
        'name': name,
        'url': url,
        'url_resolved': urlResolved,
        'homepage': homepage,
        'favicon': favicon,
        'tags': tags,
        'country': country,
        'countrycode': countryCode,
        'state': state,
        'language': language,
        'languagecodes': languageCodes,
        'votes': votes,
        'codec': codec,
        'bitrate': bitrate,
        'hls': hls ? 1 : 0,
        'lastcheckok': lastCheckOk ? 1 : 0,
        'clickcount': clickCount,
        'clicktrend': clickTrend,
        'lastchangetime_iso8601': lastChangeTime.toIso8601String(),
        'clicktimestamp_iso8601': clickTime.toIso8601String(),
        'favorite': favorite,
      };
}